### ISSUE TITLE
Why not contribute to ASDF instead?

### ISSUE THREAD

**Issue by ghostsquad** [devopspass/devopspass#1]
I read the email:

> Do you know that feeling, when Terraform complaining on wrong state file version?
>
> Folks from OpenTofu Tools team created wonderful tool - tenv. We did integration for it, so you can manage versions of Terraform, OpenTofu and TerraGrunt from UI or cli.
>
> How and why you dont need tfenv anymore, read in our new blog post.

[ASDF](https://asdf-vm.com/) immediately came to mind, as it has been my go to for managing versions, keeping those versions in-sync with source control, and it can manage nearly anything.

**Comment by devopspass** [comment]
Oh....my....GOSH!!

Man, I have to make investigation about ASDF, never saw it before...Looks like it will give me bunch of integrations at once!
Thanks a lot.

Will return back in some time.

**Comment by devopspass** [comment]
Heh, it doesn't support Windows (not WSL), right?

**Comment by ghostsquad** [comment]
> Heh, it doesn't support Windows (not WSL), right?

It's basically just a bunch of bash scripts, so yes, WSL is the way to go there.
