### ISSUE TITLE
I have never subscribed to your mailing list

### ISSUE THREAD

**Issue by qexat** [devopspass/devopspass#2]
Hello, hoping this issue will be brought to actual humans...

Why did I got signed in for your mailing list? I have never given my consent, never subscribed in any way, I am not even interested in these technologies. I am a EU resident ; do you realize that I *could* sue you over this?

Because my email is easily available on my GitHub does **not** mean you can take it freely and do whatever you want with it.
So for your own interest, please do not do that again, to anyone. What you will get is only angry, frustrated devs that would hesitate way less before going into legal action.

Have a great day.

**Comment by devopspass** [comment]
Hi @qexat, there is no bot's only real people here. 
There is no technical way to identify you as EU citizen, sorry for that if its insulted you in any way.
Your mail been removed from our mailing list.

Thanks.
